In [3]:
weights = [0.1, 0.2, 0]

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)

print(pred)


0.9800000000000001


In [8]:
def elementwise_multiplication(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = [0] * len(vec_a)
    for i in range(len(vec_a)):
        output[i] = vec_a[i] * vec_b[i]
    return output

def elementwise_addition(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = [0] * len(vec_a)
    for i in range(len(vec_a)):
        output[i] = vec_a[i] + vec_b[i]
    return output

def vector_sum(vec_a):
    output = 0
    for i in range(len(vec_a)):
        output += vec_a[i]
    return output

def vector_average(vec_a):
    return vector_sum(vec_a) / len(vec_a)

print(elementwise_multiplication(toes, wlrec))
print(elementwise_addition(toes, wlrec))
print(vector_sum(toes))
print(vector_average(toes))

def dot_product(vec_a, vec_b):
    return vector_sum(elementwise_multiplication(vec_a, vec_b))

print(dot_product(input, weights))

[5.525, 7.6000000000000005, 7.920000000000001, 8.1]
[9.15, 10.3, 10.700000000000001, 9.9]
36.9
9.225
0.9800000000000001


In [11]:
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


Making a prediction with multiple outputs

In [19]:
weights = [0.3, 0.2, 0.9]

def neural_network(input, weights):
    pred = elementwise_multiplication(input, weights)
    return pred

print(neural_network(input, weights))

[2.55, 0.13, 1.08]


Predicting with multiple inputs and outputs

In [23]:
weights = [[0.1, 0.1, -0.3],
           [0.1, 0.2, 0.0],
           [0.0, 1.3, 0.1]]

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0] * len(vect)
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)

print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


Predicting on predictions

In [37]:
import numpy as np

# toes % win # fans
ih_wgt = np.array([
    [0.1, 0.2, -0.1],   # hid[0]
    [-0.1, 0.1, 0.9],   # hid[1]
    [0.1, 0.4, 0.1]]).T # hid[2]

hp_wgt = np.array([
    [0.3, 1.1, -0.3],   # hurt?
    [0.1, 0.2, 0.0],    # win?
    [0.0, 1.3, 0.1]]).T # sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)

print(pred)

# Misc
print(ih_wgt)
print(hp_wgt)
print(ih_wgt + hp_wgt)
print(ih_wgt - hp_wgt)
print(ih_wgt * hp_wgt)
print(ih_wgt.dot(hp_wgt))

print(np.random.rand(2, 5))

[0.2135 0.145  0.5065]
[[ 0.1 -0.1  0.1]
 [ 0.2  0.1  0.4]
 [-0.1  0.9  0.1]]
[[ 0.3  0.1  0. ]
 [ 1.1  0.2  1.3]
 [-0.3  0.   0.1]]
[[ 0.4  0.   0.1]
 [ 1.3  0.3  1.7]
 [-0.4  0.9  0.2]]
[[-0.2 -0.2  0.1]
 [-0.9 -0.1 -0.9]
 [ 0.2  0.9  0. ]]
[[ 0.03 -0.01  0.  ]
 [ 0.22  0.02  0.52]
 [ 0.03  0.    0.01]]
[[-0.11 -0.01 -0.12]
 [ 0.05  0.04  0.17]
 [ 0.93  0.17  1.18]]
[[0.24093361 0.77867155 0.8863108  0.11389115 0.91580189]
 [0.21557381 0.41959147 0.35932928 0.23703092 0.83298435]]
